# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Login(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(324, 280)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(130, 100, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #565656;")
        self.label_2.setObjectName("label_2")
        self.passwordEdit = QtWidgets.QLineEdit(Form)
        self.passwordEdit.setGeometry(QtCore.QRect(50, 130, 221, 20))
        self.passwordEdit.setStyleSheet("border: 1px solid rgb(0, 132, 255);\n"
                                        "border-radius: 10px;")
        self.passwordEdit.setObjectName("passwordEdit")
        self.loginEdit = QtWidgets.QLineEdit(Form)
        self.loginEdit.setGeometry(QtCore.QRect(20, 60, 281, 20))
        self.loginEdit.setStyleSheet("border: 1px solid rgb(0, 132, 255);\n"
                                     "border-radius: 10px;")
        self.loginEdit.setObjectName("loginEdit")
        self.loginButton = QtWidgets.QPushButton(Form)
        self.loginButton.setGeometry(QtCore.QRect(20, 180, 281, 23))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton {\n"
                                       "    background-color: rgb(0, 132, 255);\n"
                                       "    border-radius: 9px;\n"
                                       "    color: #fff;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(0, 166, 255);\n"
                                       "}\n"
                                       "")
        self.loginButton.setObjectName("loginButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(130, 30, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #565656;")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 250, 81, 16))
        self.label_3.setStyleSheet("color: #565656;")
        self.label_3.setObjectName("label_3")
        self.registrationButton = QtWidgets.QPushButton(Form)
        self.registrationButton.setGeometry(QtCore.QRect(160, 250, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.registrationButton.setFont(font)
        self.registrationButton.setStyleSheet("QPushButton{\n"
                                              "    border: none;\n"
                                              "}\n"
                                              "QPushButton:hover{\n"
                                              "    color: rgb(0, 132, 255);\n"
                                              "}")
        self.registrationButton.setObjectName("registrationButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Пароль"))
        self.loginButton.setText(_translate("Form", "Войти"))
        self.label.setText(_translate("Form", "Логин"))
        self.label_3.setText(_translate("Form", "Нет аккаунта? "))
        self.registrationButton.setText(_translate("Form", "Зарегистрируйся!"))
